#!/usr/bin/env bash
#
# RepoInsight AI — One-command setup
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh
#
# This script will:
#   1. Check that Docker is installed and running
#   2. Ask you for your API keys
#   3. Create the .env file
#   4. Build and start everything
#

set -e

# ── Colors ────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

echo ""
echo -e "${CYAN}${BOLD}╔═══════════════════════════════════════════╗${RESET}"
echo -e "${CYAN}${BOLD}║       RepoInsight AI — Setup Script       ║${RESET}"
echo -e "${CYAN}${BOLD}╚═══════════════════════════════════════════╝${RESET}"
echo ""

# ── Step 1: Check Docker ─────────────────────────────
echo -e "${BOLD}[1/4] Checking Docker...${RESET}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}Docker is not installed.${RESET}"
    echo ""
    echo "Install Docker Desktop from: https://www.docker.com/products/docker-desktop/"
    echo "After installing, open Docker Desktop and wait for it to start,"
    echo "then run this script again."
    exit 1
fi

if ! docker info &> /dev/null; then
    echo -e "${RED}Docker is installed but not running.${RESET}"
    echo ""
    echo "Open Docker Desktop and wait for it to start, then run this script again."
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo -e "${RED}Docker Compose is not available.${RESET}"
    echo "Update Docker Desktop to the latest version (Compose is built in)."
    exit 1
fi

echo -e "${GREEN}  ✓ Docker is installed and running${RESET}"
echo ""

# ── Step 2: Collect API keys ─────────────────────────
echo -e "${BOLD}[2/4] Setting up API keys...${RESET}"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo -e "${YELLOW}  .env file already exists.${RESET}"
    read -p "  Overwrite it? (y/n): " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        echo "  Keeping existing .env file."
        echo ""
        SKIP_ENV=true
    fi
fi

if [ "$SKIP_ENV" != "true" ]; then
    echo "  You need two things:"
    echo ""
    echo "  1. Anthropic API key (FREE with Claude Pro subscription)"
    echo "     Get one at: https://console.anthropic.com/settings/keys"
    echo ""
    echo "  2. GitHub OAuth app (optional — needed for GitHub login)"
    echo "     Create one at: https://github.com/settings/developers"
    echo "     Set callback URL to: http://localhost:3000/auth/github/callback"
    echo ""
    echo "  Note: Embeddings run locally for free — no API key needed for indexing."
    echo ""

    # Anthropic key
    read -p "  Enter your Anthropic API key (starts with sk-ant-): " ANTHROPIC_KEY
    if [ -z "$ANTHROPIC_KEY" ]; then
        echo -e "${YELLOW}  No key entered — chat/docs/tasks won't work until you add one.${RESET}"
        ANTHROPIC_KEY="not-set"
    fi

    # GitHub OAuth (optional)
    echo ""
    read -p "  Enter GitHub OAuth Client ID (press Enter to skip): " GH_CLIENT_ID
    read -p "  Enter GitHub OAuth Client Secret (press Enter to skip): " GH_CLIENT_SECRET

    if [ -z "$GH_CLIENT_ID" ]; then
        GH_CLIENT_ID="not-set"
        GH_CLIENT_SECRET="not-set"
        echo -e "${YELLOW}  Skipping GitHub OAuth — you can still register with email/password.${RESET}"
    fi

    # Generate a random JWT secret
    JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || echo "local-dev-secret-change-in-production-$(date +%s)")

    # Write the .env file
    cat > .env << EOF
# ─── Generated by setup.sh ───────────────────────────
APP_ENV=development
DEBUG=true

# Database (don't change these — they match docker-compose.yml)
DATABASE_URL=postgresql+asyncpg://repoinsight:repoinsight@db:5432/repoinsight
DATABASE_URL_SYNC=postgresql://repoinsight:repoinsight@db:5432/repoinsight
POSTGRES_USER=repoinsight
POSTGRES_PASSWORD=repoinsight
POSTGRES_DB=repoinsight

# Redis
REDIS_URL=redis://redis:6379/0

# Auth
JWT_SECRET=${JWT_SECRET}
JWT_ALGORITHM=HS256
JWT_EXPIRE_MINUTES=1440

# GitHub OAuth
GITHUB_CLIENT_ID=${GH_CLIENT_ID}
GITHUB_CLIENT_SECRET=${GH_CLIENT_SECRET}

# AI Chat — Claude (free with Pro subscription)
ANTHROPIC_API_KEY=${ANTHROPIC_KEY}
ANTHROPIC_MODEL=claude-sonnet-4-20250514

# OpenAI (optional fallback — requires paid credits)
OPENAI_API_KEY=not-set
OPENAI_MODEL=gpt-4o
OPENAI_EMBEDDING_MODEL=text-embedding-3-small

# ChromaDB (internal Docker network, don't change)
CHROMA_HOST=chroma
CHROMA_PORT=8000

# Frontend
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_APP_URL=http://localhost:3000

# Rate Limiting
RATE_LIMIT_PER_MINUTE=60
EOF

    echo ""
    echo -e "${GREEN}  ✓ .env file created${RESET}"
fi

echo ""

# ── Step 3: Build ─────────────────────────────────────
echo -e "${BOLD}[3/4] Building containers (this takes 3-5 minutes the first time)...${RESET}"
echo ""

docker compose build --progress=plain 2>&1 | tail -5
echo ""
echo -e "${GREEN}  ✓ Build complete${RESET}"
echo ""

# ── Step 4: Start ─────────────────────────────────────
echo -e "${BOLD}[4/4] Starting all services...${RESET}"
echo ""

docker compose up -d

echo ""
echo "  Waiting for services to be healthy..."
sleep 5

# Wait for the API to come up (max 60 seconds)
for i in $(seq 1 30); do
    if curl -s http://localhost:8000/health > /dev/null 2>&1; then
        break
    fi
    sleep 2
    echo -n "."
done
echo ""

# Final status check
echo ""
echo -e "${CYAN}${BOLD}═══════════════════════════════════════════════${RESET}"
echo ""

if curl -s http://localhost:8000/health > /dev/null 2>&1; then
    echo -e "${GREEN}${BOLD}  ✓ RepoInsight AI is running!${RESET}"
else
    echo -e "${YELLOW}${BOLD}  ⚠ API is still starting up — give it another minute.${RESET}"
    echo "  Run 'docker compose logs api' to check progress."
fi

echo ""
echo -e "  ${BOLD}Open in your browser:${RESET}"
echo ""
echo -e "    App:       ${CYAN}http://localhost:3000${RESET}"
echo -e "    API docs:  ${CYAN}http://localhost:8000/docs${RESET}"
echo ""
echo -e "  ${BOLD}Useful commands:${RESET}"
echo ""
echo "    docker compose logs -f        # watch all logs"
echo "    docker compose logs -f api    # watch API logs only"
echo "    docker compose ps             # check service status"
echo "    docker compose down           # stop everything"
echo "    docker compose down -v        # stop + delete data"
echo ""
echo -e "${CYAN}${BOLD}═══════════════════════════════════════════════${RESET}"
echo ""
