# RepoInsight AI — Windows Setup Script
#
# Usage:
#   Right-click this file → "Run with PowerShell"
#   Or open PowerShell and run:  .\setup.ps1
#

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "  ╔═══════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "  ║       RepoInsight AI — Setup Script       ║" -ForegroundColor Cyan
Write-Host "  ╚═══════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ── Step 1: Check Docker ─────────────────────────────
Write-Host "[1/4] Checking Docker..." -ForegroundColor White

try {
    docker info 2>&1 | Out-Null
    docker compose version 2>&1 | Out-Null
    Write-Host "  Docker is installed and running" -ForegroundColor Green
} catch {
    Write-Host "  Docker is not installed or not running." -ForegroundColor Red
    Write-Host ""
    Write-Host "  Install Docker Desktop from: https://www.docker.com/products/docker-desktop/"
    Write-Host "  After installing, open Docker Desktop and wait for it to start."
    Write-Host "  Then run this script again."
    Read-Host "  Press Enter to exit"
    exit 1
}

Write-Host ""

# ── Step 2: Collect API keys ─────────────────────────
Write-Host "[2/4] Setting up API keys..." -ForegroundColor White
Write-Host ""

$skipEnv = $false
if (Test-Path .env) {
    Write-Host "  .env file already exists." -ForegroundColor Yellow
    $overwrite = Read-Host "  Overwrite it? (y/n)"
    if ($overwrite -ne "y") {
        Write-Host "  Keeping existing .env file."
        $skipEnv = $true
    }
}

if (-not $skipEnv) {
    Write-Host "  You need two things (both are free to set up):"
    Write-Host ""
    Write-Host "  1. OpenAI API key"
    Write-Host "     Get one at: https://platform.openai.com/api-keys"
    Write-Host ""
    Write-Host "  2. GitHub OAuth app (optional)"
    Write-Host "     Create at: https://github.com/settings/developers"
    Write-Host "     Callback URL: http://localhost:3000/auth/github/callback"
    Write-Host ""

    $openaiKey = Read-Host "  Enter your OpenAI API key (starts with sk-)"
    if ([string]::IsNullOrEmpty($openaiKey)) {
        Write-Host "  No key entered — AI features won't work until you add one." -ForegroundColor Yellow
        $openaiKey = "sk-placeholder-replace-me"
    }

    Write-Host ""
    $ghClientId = Read-Host "  GitHub OAuth Client ID (Enter to skip)"
    $ghClientSecret = Read-Host "  GitHub OAuth Client Secret (Enter to skip)"

    if ([string]::IsNullOrEmpty($ghClientId)) {
        $ghClientId = "not-set"
        $ghClientSecret = "not-set"
        Write-Host "  Skipping GitHub OAuth. You can register with email/password." -ForegroundColor Yellow
    }

    # Generate JWT secret
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $jwtSecret = [System.BitConverter]::ToString($bytes).Replace("-","").ToLower()

    $envContent = @"
# Generated by setup.ps1
APP_ENV=development
DEBUG=true

DATABASE_URL=postgresql+asyncpg://repoinsight:repoinsight@db:5432/repoinsight
DATABASE_URL_SYNC=postgresql://repoinsight:repoinsight@db:5432/repoinsight
POSTGRES_USER=repoinsight
POSTGRES_PASSWORD=repoinsight
POSTGRES_DB=repoinsight

REDIS_URL=redis://redis:6379/0

JWT_SECRET=$jwtSecret
JWT_ALGORITHM=HS256
JWT_EXPIRE_MINUTES=1440

GITHUB_CLIENT_ID=$ghClientId
GITHUB_CLIENT_SECRET=$ghClientSecret

OPENAI_API_KEY=$openaiKey
OPENAI_MODEL=gpt-4o
OPENAI_EMBEDDING_MODEL=text-embedding-3-small

CHROMA_HOST=chroma
CHROMA_PORT=8000

NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_APP_URL=http://localhost:3000

RATE_LIMIT_PER_MINUTE=60
"@

    Set-Content -Path .env -Value $envContent -Encoding UTF8
    Write-Host ""
    Write-Host "  .env file created" -ForegroundColor Green
}

Write-Host ""

# ── Step 3: Build ─────────────────────────────────────
Write-Host "[3/4] Building containers (3-5 minutes first time)..." -ForegroundColor White
Write-Host ""

docker compose build
Write-Host ""
Write-Host "  Build complete" -ForegroundColor Green
Write-Host ""

# ── Step 4: Start ─────────────────────────────────────
Write-Host "[4/4] Starting all services..." -ForegroundColor White
Write-Host ""

docker compose up -d

Write-Host ""
Write-Host "  Waiting for services to start..."
Start-Sleep -Seconds 10

# Check health
$healthy = $false
for ($i = 0; $i -lt 20; $i++) {
    try {
        $resp = Invoke-RestMethod -Uri http://localhost:8000/health -TimeoutSec 3 -ErrorAction Stop
        if ($resp.status -eq "healthy") {
            $healthy = $true
            break
        }
    } catch {}
    Start-Sleep -Seconds 3
    Write-Host "." -NoNewline
}
Write-Host ""

Write-Host ""
Write-Host "  ═══════════════════════════════════════════" -ForegroundColor Cyan

if ($healthy) {
    Write-Host ""
    Write-Host "  RepoInsight AI is running!" -ForegroundColor Green
} else {
    Write-Host ""
    Write-Host "  API is still starting — give it another minute." -ForegroundColor Yellow
    Write-Host "  Run 'docker compose logs api' to check progress."
}

Write-Host ""
Write-Host "  Open in your browser:"
Write-Host ""
Write-Host "    App:       http://localhost:3000" -ForegroundColor Cyan
Write-Host "    API docs:  http://localhost:8000/docs" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Useful commands:"
Write-Host ""
Write-Host "    docker compose logs -f        # watch all logs"
Write-Host "    docker compose ps             # check service status"
Write-Host "    docker compose down           # stop everything"
Write-Host "    docker compose down -v        # stop + delete data"
Write-Host ""
Write-Host "  ═══════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

Read-Host "  Press Enter to close"
